F1
MatviiBoichenko/ConsoleFileManager pull request #2
Opened 2021-12-31 10:36 UTC by MatviiBoichenko

Second try in pull requesting. Logic is in ConsoleFileManager class. Interface is in Program class. Tests are in TestingConsoleFileManager class.

2022-01-06 16:47 UTC, Gribok4E requested changes
Пожалуйста, добавь гитигнор

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                return e.GetType().Name;
если что, можно просто написать e.Message

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                return e.GetType().Name;
если что, можно просто написать e.Message

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +            return false;
перед return отступ

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                return !Directory.Exists(directoryName);
перед return отступ

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +            return false;
перед return отступ

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                return Directory.Exists(newPath);
перед return отступ

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                newPath = currentPath + newPath;
это не js, добавляй фигурные скобки

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +            return false;
перед return отступ

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                return Directory.Exists(newDirectoryName);
перед return отступ

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                pathToFiles = currentPath + pathToFiles+"/";
это не js, добавляй фигурные скобки

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                Console.WriteLine("File will be overwritten");
это не js, добавляй фигурные скобки

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +            return File.Exists(newFilePosition);
перед return отступ

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                newPath = currentPath + newPath;
это не js, добавляй фигурные скобки

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                return File.Exists(newPath);
перед return отступ

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +            return false;
перед return отступ

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                filePosition = currentPath + filePosition;
это не js, добавляй фигурные скобки

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                return !File.Exists(filePosition);
перед return отступ

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +            return false;
перед return отступ

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                pathToFile = currentPath + pathToFile;
это не js, добавляй фигурные скобки

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +            return String.Join("", content);
перед return отступ

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                return "Directory to be searched in doesn't exist";
это не js, добавляй фигурные скобки

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +            foreach (var f in files)
перед foreach отступ

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/IFileManager.cs
> +        public string GetHelp();
модификаторы доступа не нужны

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/Program.cs
> +            string command = "";
Юзай String.Empty вместо ""

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/src/Program.cs
> +                Console.ForegroundColor = ConsoleColor.Yellow;
Метод очень длинный, по стайлгайдам должен быть не больше 40 строк

2022-01-06 16:47 UTC, Gribok4E commented on ConsoleFileManager/ConsoleFileManager/test/TestingConsoleFileManager.cs
> +    }
помимо положительный тестов, тебе нужны тесты, которые будут возвращать отрицательный результат

2022-01-06 19:13 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                return e.GetType().Name;
я это делаю чтоб не сообщение об ошибке получать, а только название словленой ошибки, это используется в тестах

2022-01-06 19:13 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +            return false;
исправил

2022-01-06 19:13 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                return !Directory.Exists(directoryName);
исправил

2022-01-06 19:13 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +            return false;
исправил

2022-01-06 19:13 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +            foreach (var f in files)
исправил

2022-01-06 19:13 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/IFileManager.cs
> +        public string GetHelp();
исправил

2022-01-06 19:13 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/Program.cs
> +            string command = "";
исправил

2022-01-06 19:14 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/Program.cs
> +                Console.ForegroundColor = ConsoleColor.Yellow;
исправил

2022-01-06 19:14 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                return Directory.Exists(newPath);
исправил

2022-01-06 19:14 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                newPath = currentPath + newPath;
исправил

2022-01-06 19:14 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +            return false;
исправил

2022-01-06 19:14 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                return Directory.Exists(newDirectoryName);
исправил

2022-01-06 19:14 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                Console.WriteLine("File will be overwritten");
исправил

2022-01-06 19:15 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +            return File.Exists(newFilePosition);
исправил

2022-01-06 19:15 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                newPath = currentPath + newPath;
исправил

2022-01-06 19:15 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                return File.Exists(newPath);
исправил

2022-01-06 19:15 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +            return false;
исправил

2022-01-06 19:15 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                filePosition = currentPath + filePosition;
исправил

2022-01-06 19:15 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                return !File.Exists(filePosition);
исправил

2022-01-06 19:15 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +            return false;
исправил

2022-01-06 19:15 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                pathToFile = currentPath + pathToFile;
исправил

2022-01-06 19:15 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +            return String.Join("", content);
исправил

2022-01-06 19:15 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/src/ConsoleFileManager.cs
> +                return "Directory to be searched in doesn't exist";
исправил

2022-01-06 19:17 UTC, MatviiBoichenko commented on ConsoleFileManager/ConsoleFileManager/test/TestingConsoleFileManager.cs
> +    }
там же есть ассерты на отрицательный результат нет? или что иное имеется в виду?

2022-01-07 15:57 UTC, Gribok4E approved these changes

2022-01-07 15:57 UTC, merged